trigger:
- main

pool:
  vmImage: ubuntu-latest
  name:      MyAgentsPool
variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'fd270672-6d6d-4d57-9b35-ba5cd9e93377'
  # Web app name
  webAppName: 'KminstLTD'
  # Environment name
  environmentName: 'KminstLTD'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'  

stages:
 - stage: Build
   displayName: Build stage
   jobs:
     - job: MavenPackageAndPlublishArtifacts
       displayName: Build MywebApp Application
       pool:
         vmImageName: 'ubuntu-latest'
         name: 'MyAgentsPool'
       steps:
        - task: Maven@3
          displayName: Maven Package and MavenPackageAndPublishArtifacts
          inputs:
            mavenPomFile: 'MyWebApp/pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: PublishBuildArtifacts@1
          inputs:
           pathtoPublish: dist
           ArtifactName: 'dist'
 