# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pool:
  name:myAgentsPool

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'f03eb2fe-dbe4-45c4-9889-5472b1526984'

  # Web app name
  webAppName: 'KminstLTD'

  # Environment name
  environmentName: 'KminstLTD'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)
      name: myAgentsPool

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'MyWebApp/pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(KmintsLTD)
    pool:
      vmImage: $(vmImageName)
      name: myAgentsPool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: Deploy build to KminstLTD'
            inputs:
              azureSubscription: $ 'Azure subscription 1(1696d09c-6a2d-4741-b83f-6709584755e7)'
              appType: webAppLinux
              appName: $(KmintsLTD)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)/drop'
